version: '3.1'

volumes:
    prometheus_data: {}
    grafana_data: {}
    prometheus_config_data: {}
    alertmanager_config_data: {}

networks:
  front-tier:
  back-tier:

services:

  prometheus:
    image: prom/prometheus:v2.0.0
    volumes:
      - prometheus_config_data:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    links:
      - cadvisor:cadvisor
      - alertmanager:alertmanager
    networks:
      - back-tier
    restart: always
    deploy:
      placement:
        constraints:
          - node.hostname == ${HOSTNAME}
