version: '3.1'

volumes:
    prometheus_data: {}
    grafana_data: {}
    prometheus_config_data: {}
    alertmanager_config_data: {}

networks:
  front-tier:
  back-tier:

services:

  prometheus:
    image: batfish/allinone
    ports:
      - 8888:8888
    networks:
      - back-tier
    restart: always
    deploy:
      placement:
        constraints:
          - node.hostname == ${HOSTNAME}
