version: '3.1'

services:
  batfish:
    image: batfish/allinone
    ports:
      - 8888:8888
    restart: always
    deploy:
      placement:
        constraints:
          - node.hostname == ${HOSTNAME}
