version: 2
jobs:
  build:
    docker:
      - image: akira6592/ansible
    steps:
      - checkout
      - run:
          name: ansible-lint
          command: f"ind  ./ -name '*.yml' | xargs ansible-lint"
