version: 2
jobs:
  build:
    docker:
      - image: ansible/ansible:ubuntu1604
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'ansible-playbook test.yml --syntac-check'
