version: 2
jobs:
  build:
    docker:
      - image: ansible/centos7-ansible
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'ansible-playbook -i localhost, test.yml --syntax-check'
